language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "4"
  - "6"
  - "7"
notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
after_success:
  - npm install -g codecov
  - codecov

